databases:
  - name: qnasite
    plan: free
    databaseName: qnasite
    user: qnauser

services:
  - type: web
    plan: free
    name: qnasite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn qnasite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qnasitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ENV_NAME
        value: production
